sudo: false
language: ruby
install: bundle install
cache: bundler
script: bundle exec jekyll build
before_deploy:
  pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync _site s3://aws-website-kahweecom-3r334 --region=us-east-1 --delete
  skip_cleanup: true
